/**
 * LinkIOT Dashboard
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient, HttpHeaders, HttpParams,
  HttpResponse, HttpEvent
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs/Observable';

import { AlarmLog } from '../model/alarmLog';
import { Body } from '../model/body';
import { Body1 } from '../model/body1';
import { Body2 } from '../model/body2';
import { Body3 } from '../model/body3';
import { Body4 } from '../model/body4';
import { Body5 } from '../model/body5';
import { Body6 } from '../model/body6';
import { Count } from '../model/count';
import { Data } from '../model/data';
import { Device } from '../model/device';
import { DeviceDetail } from '../model/deviceDetail';
import { DeviceState } from '../model/deviceState';
import { Sensor } from '../model/sensor';
import { SimpleStatus } from '../model/simpleStatus';
import { User } from '../model/user';
import { UserLog } from '../model/userLog';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';


@Injectable()
export class DefaultService {

  protected basePath = 'http://link.hdussta.cn:7778/v1';
  // protected basePath = 'http://localhost/v1';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
    this.configuration.withCredentials = true;
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }


  /**
   * 统计报警历史
   *
   * @param level
   * @param deviceId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public countAlarmLogs(level?: number, deviceId?: string, observe?: 'body', reportProgress?: boolean): Observable<Count>;
  public countAlarmLogs(level?: number, deviceId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Count>>;
  public countAlarmLogs(level?: number, deviceId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Count>>;
  public countAlarmLogs(level?: number, deviceId?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (level !== undefined && level !== null) {
      queryParameters = queryParameters.set('level', <any>level);
    }
    if (deviceId !== undefined && deviceId !== null) {
      queryParameters = queryParameters.set('deviceId', <any>deviceId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/log/alarm/count`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 统计传感器数据
   *
   * @param deviceId
   * @param sensorId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public countData(deviceId: string, sensorId: number, observe?: 'body', reportProgress?: boolean): Observable<Count>;
  public countData(deviceId: string, sensorId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Count>>;
  public countData(deviceId: string, sensorId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Count>>;
  public countData(deviceId: string, sensorId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling countData.');
    }
    if (sensorId === null || sensorId === undefined) {
      throw new Error('Required parameter sensorId was null or undefined when calling countData.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/sensor/data/count/${encodeURIComponent(String(deviceId))}/${encodeURIComponent(String(sensorId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 统计设备
   *
   * @param deviceId
   * @param name
   * @param observe
   * @param reportProgress
   */
  public countDevices(deviceId?: string, name?: string, observe?: 'body', reportProgress?: boolean): Observable<Count>;
  public countDevices(deviceId?: string, name?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Count>>;
  public countDevices(deviceId?: string, name?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Count>>;
  public countDevices(deviceId?: string, name?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }
    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (deviceId !== undefined && deviceId !== null) {
      queryParameters = queryParameters.set('deviceId', deviceId + '%');
    }

    if (name !== undefined && name !== null) {
      queryParameters = queryParameters.set('name', name + '%');
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/devices/count`,
      {
        params:queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 统计传感器
   *
   * @param deviceId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public countSensors(deviceId: string, observe?: 'body', reportProgress?: boolean): Observable<Count>;
  public countSensors(deviceId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Count>>;
  public countSensors(deviceId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Count>>;
  public countSensors(deviceId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling countSensors.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/sensors/count/${encodeURIComponent(String(deviceId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 统计用户
   *
   * @param adminId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public countUser(adminId?: number, observe?: 'body', reportProgress?: boolean): Observable<Count>;
  public countUser(adminId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Count>>;
  public countUser(adminId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Count>>;
  public countUser(adminId?: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (adminId !== undefined && adminId !== null) {
      queryParameters = queryParameters.set('adminId', <any>adminId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/admin/user/count`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 统计用户日志
   *
   * @param username
   * @param type
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public countUserLogs(username?: string, type?: number, observe?: 'body', reportProgress?: boolean): Observable<Count>;
  public countUserLogs(username?: string, type?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Count>>;
  public countUserLogs(username?: string, type?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Count>>;
  public countUserLogs(username?: string, type?: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (username !== undefined && username !== null) {
      queryParameters = queryParameters.set('username', username + '%');
    }
    if (type !== undefined && type !== null) {
      queryParameters = queryParameters.set('type', <any>type);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/log/user/count`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 删除用户
   *
   * @param username 用户名
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public delUser(username?: string, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public delUser(username?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public delUser(username?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public delUser(username?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (username !== undefined && username !== null) {
      queryParameters = queryParameters.set('username', <any>username);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.delete(`${this.basePath}/user`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 删除报警日志
   *
   * @param logId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteAlarmLog(logId: number, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public deleteAlarmLog(logId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public deleteAlarmLog(logId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public deleteAlarmLog(logId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (logId === null || logId === undefined) {
      throw new Error('Required parameter logId was null or undefined when calling deleteAlarmLog.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (logId !== undefined && logId !== null) {
      queryParameters = queryParameters.set('logId', <any>logId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.delete(`${this.basePath}/log/alarm`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 删除设备
   *
   * @param deviceId 设备ID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteDevice(deviceId: string, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public deleteDevice(deviceId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public deleteDevice(deviceId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public deleteDevice(deviceId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling deleteDevice.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (deviceId !== undefined && deviceId !== null) {
      queryParameters = queryParameters.set('deviceId', <any>deviceId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.delete(`${this.basePath}/db/devices`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 删除传感器
   *
   * @param deviceId 设备ID
   * @param sensorId 传感器ID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteSensor(deviceId: string, sensorId: number, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public deleteSensor(deviceId: string, sensorId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public deleteSensor(deviceId: string, sensorId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public deleteSensor(deviceId: string, sensorId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling deleteSensor.');
    }
    if (sensorId === null || sensorId === undefined) {
      throw new Error('Required parameter sensorId was null or undefined when calling deleteSensor.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (sensorId !== undefined && sensorId !== null) {
      queryParameters = queryParameters.set('sensorId', <any>sensorId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.delete(`${this.basePath}/db/sensors/${encodeURIComponent(String(deviceId))}`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 强制下线设备
   *
   * @param deviceId 设备ID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public forceClose(deviceId: string, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public forceClose(deviceId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public forceClose(deviceId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public forceClose(deviceId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling forceClose.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/device/close/${encodeURIComponent(String(deviceId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 获取报警历史
   *
   * @param offset
   * @param limit
   * @param level
   * @param deviceId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAlarmLogs(offset: number, limit: number, level?: number, deviceId?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<AlarmLog>>;
  public getAlarmLogs(offset: number, limit: number, level?: number, deviceId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AlarmLog>>>;
  public getAlarmLogs(offset: number, limit: number, level?: number, deviceId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AlarmLog>>>;
  public getAlarmLogs(offset: number, limit: number, level?: number, deviceId?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (offset === null || offset === undefined) {
      throw new Error('Required parameter offset was null or undefined when calling getAlarmLogs.');
    }
    if (limit === null || limit === undefined) {
      throw new Error('Required parameter limit was null or undefined when calling getAlarmLogs.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (offset !== undefined && offset !== null) {
      queryParameters = queryParameters.set('offset', <any>offset);
    }
    if (limit !== undefined && limit !== null) {
      queryParameters = queryParameters.set('limit', <any>limit);
    }
    if (level !== undefined && level !== null) {
      queryParameters = queryParameters.set('level', <any>level);
    }
    if (deviceId !== undefined && deviceId !== null) {
      queryParameters = queryParameters.set('deviceId', <any>deviceId);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/log/alarm`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 获取设备详细信息
   *
   * @param deviceId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getDeviceDetail(deviceId: string, observe?: 'body', reportProgress?: boolean): Observable<DeviceDetail>;
  public getDeviceDetail(deviceId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DeviceDetail>>;
  public getDeviceDetail(deviceId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DeviceDetail>>;
  public getDeviceDetail(deviceId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling getDeviceDetail.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/device/${encodeURIComponent(String(deviceId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 用户登录
   *
   * @param user 用户名
   * @param pass 密码
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getLogin(user: string, pass: string, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public getLogin(user: string, pass: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public getLogin(user: string, pass: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public getLogin(user: string, pass: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (user === null || user === undefined) {
      throw new Error('Required parameter user was null or undefined when calling getLogin.');
    }
    if (pass === null || pass === undefined) {
      throw new Error('Required parameter pass was null or undefined when calling getLogin.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (user !== undefined && user !== null) {
      queryParameters = queryParameters.set('user', <any>user);
    }
    if (pass !== undefined && pass !== null) {
      queryParameters = queryParameters.set('pass', <any>pass);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/auth/login`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 用户登出
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getLogout(observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public getLogout(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public getLogout(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public getLogout(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/auth/logout`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 某一个设备的传感器列表
   *
   * @param deviceId 设备ID
   * @param offset 列表起始位置
   * @param limit 记录数量
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getSensors(deviceId: string, offset: number, limit: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Sensor>>;
  public getSensors(deviceId: string, offset: number, limit: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Sensor>>>;
  public getSensors(deviceId: string, offset: number, limit: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Sensor>>>;
  public getSensors(deviceId: string, offset: number, limit: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling getSensors.');
    }
    if (offset === null || offset === undefined) {
      throw new Error('Required parameter offset was null or undefined when calling getSensors.');
    }
    if (limit === null || limit === undefined) {
      throw new Error('Required parameter limit was null or undefined when calling getSensors.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (offset !== undefined && offset !== null) {
      queryParameters = queryParameters.set('offset', <any>offset);
    }
    if (limit !== undefined && limit !== null) {
      queryParameters = queryParameters.set('limit', <any>limit);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/sensors/${encodeURIComponent(String(deviceId))}`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 获取当前设备状态
   *
   * @param deviceId 设备ID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getState(deviceId: string, observe?: 'body', reportProgress?: boolean): Observable<DeviceState>;
  public getState(deviceId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DeviceState>>;
  public getState(deviceId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DeviceState>>;
  public getState(deviceId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling getState.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/device/state/${encodeURIComponent(String(deviceId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 查询用户信息
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getUser(observe?: 'body', reportProgress?: boolean): Observable<User>;
  public getUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
  public getUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
  public getUser(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/user`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 获取用户日志
   *
   * @param offset
   * @param limit
   * @param username
   * @param type 日志类型
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getUserLogs(offset: number, limit: number, username?: string, type?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<UserLog>>;
  public getUserLogs(offset: number, limit: number, username?: string, type?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserLog>>>;
  public getUserLogs(offset: number, limit: number, username?: string, type?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserLog>>>;
  public getUserLogs(offset: number, limit: number, username?: string, type?: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (offset === null || offset === undefined) {
      throw new Error('Required parameter offset was null or undefined when calling getUserLogs.');
    }
    if (limit === null || limit === undefined) {
      throw new Error('Required parameter limit was null or undefined when calling getUserLogs.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (offset !== undefined && offset !== null) {
      queryParameters = queryParameters.set('offset', <any>offset);
    }
    if (limit !== undefined && limit !== null) {
      queryParameters = queryParameters.set('limit', <any>limit);
    }
    if (username !== undefined && username !== null) {
      queryParameters = queryParameters.set('username', username + '%');
    }
    if (type !== undefined && type !== null) {
      queryParameters = queryParameters.set('type', <any>type);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/log/user`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 获取传感器数据
   *
   * @param deviceId 设备ID
   * @param sensorId 传感器ID
   * @param offset 数据列表起始位置
   * @param limit 数据列表记录数
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public listData(deviceId: string, sensorId: number, offset: number, limit: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Data>>;
  public listData(deviceId: string, sensorId: number, offset: number, limit: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Data>>>;
  public listData(deviceId: string, sensorId: number, offset: number, limit: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Data>>>;
  public listData(deviceId: string, sensorId: number, offset: number, limit: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling listData.');
    }
    if (sensorId === null || sensorId === undefined) {
      throw new Error('Required parameter sensorId was null or undefined when calling listData.');
    }
    if (offset === null || offset === undefined) {
      throw new Error('Required parameter offset was null or undefined when calling listData.');
    }
    if (limit === null || limit === undefined) {
      throw new Error('Required parameter limit was null or undefined when calling listData.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (offset !== undefined && offset !== null) {
      queryParameters = queryParameters.set('offset', <any>offset);
    }
    if (limit !== undefined && limit !== null) {
      queryParameters = queryParameters.set('limit', <any>limit);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/sensor/data/${encodeURIComponent(String(deviceId))}/${encodeURIComponent(String(sensorId))}`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 获取用户创建的所有设备
   *
   * @param offset 起始列表位置
   * @param limit 本次列表数量
   * @param deviceId
   * @param name
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public listDevices(offset: number, limit: number, deviceId?: string, name?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Device>>;
  public listDevices(offset: number, limit: number, deviceId?: string, name?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Device>>>;
  public listDevices(offset: number, limit: number, deviceId?: string, name?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Device>>>;
  public listDevices(offset: number, limit: number, deviceId?: string, name?: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (offset === null || offset === undefined) {
      throw new Error('Required parameter offset was null or undefined when calling listDevices.');
    }
    if (limit === null || limit === undefined) {
      throw new Error('Required parameter limit was null or undefined when calling listDevices.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (offset !== undefined && offset !== null) {
      queryParameters = queryParameters.set('offset', <any>offset);
    }
    if (limit !== undefined && limit !== null) {
      queryParameters = queryParameters.set('limit', <any>limit);
    }

    if (deviceId !== undefined && deviceId !== null) {
      queryParameters = queryParameters.set('deviceId', deviceId + '%');
    }

    if (name !== undefined && name !== null) {
      queryParameters = queryParameters.set('name', name + '%');
    }
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/db/devices`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 管理员列表用户
   *
   * @param offset
   * @param limit
   * @param adminId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public listUser(offset: number, limit: number, adminId?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<User>>;
  public listUser(offset: number, limit: number, adminId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<User>>>;
  public listUser(offset: number, limit: number, adminId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<User>>>;
  public listUser(offset: number, limit: number, adminId?: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (offset === null || offset === undefined) {
      throw new Error('Required parameter offset was null or undefined when calling listUser.');
    }
    if (limit === null || limit === undefined) {
      throw new Error('Required parameter limit was null or undefined when calling listUser.');
    }

    let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
    if (adminId !== undefined && adminId !== null) {
      queryParameters = queryParameters.set('adminId', <any>adminId);
    }
    if (offset !== undefined && offset !== null) {
      queryParameters = queryParameters.set('offset', <any>offset);
    }
    if (limit !== undefined && limit !== null) {
      queryParameters = queryParameters.set('limit', <any>limit);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.get(`${this.basePath}/admin/user`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 提交解决结果
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postAlarmLog(body?: Body6, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public postAlarmLog(body?: Body6, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public postAlarmLog(body?: Body6, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public postAlarmLog(body?: Body6, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post(`${this.basePath}/log/alarm`, body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 更新设备
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postDevice(body?: Body3, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public postDevice(body?: Body3, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public postDevice(body?: Body3, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public postDevice(body?: Body3, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post(`${this.basePath}/db/devices`, body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 更新传感器信息
   *
   * @param deviceId 设备ID
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postSensor(deviceId: string, body?: Body5, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public postSensor(deviceId: string, body?: Body5, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public postSensor(deviceId: string, body?: Body5, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public postSensor(deviceId: string, body?: Body5, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling postSensor.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post(`${this.basePath}/db/sensors/${encodeURIComponent(String(deviceId))}`, body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 用户设置新的设备状态
   *
   * @param body 用户设置的新状态
   * @param deviceId 设备ID
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postState(body: any, deviceId: string, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public postState(body: any, deviceId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public postState(body: any, deviceId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public postState(body: any, deviceId: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling postState.');
    }
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling postState.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post(`${this.basePath}/db/device/state/${encodeURIComponent(String(deviceId))}`, body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 修改用户信息
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postUser(body?: Body1, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public postUser(body?: Body1, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public postUser(body?: Body1, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public postUser(body?: Body1, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.post(`${this.basePath}/user`, body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 创建新的设备
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public putDevice(body?: Body2, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public putDevice(body?: Body2, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public putDevice(body?: Body2, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public putDevice(body?: Body2, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.put(`${this.basePath}/db/devices`, body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 创建传感器
   *
   * @param deviceId 设备ID
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public putSensor(deviceId: string, body?: Body4, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public putSensor(deviceId: string, body?: Body4, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public putSensor(deviceId: string, body?: Body4, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public putSensor(deviceId: string, body?: Body4, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (deviceId === null || deviceId === undefined) {
      throw new Error('Required parameter deviceId was null or undefined when calling putSensor.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.put(`${this.basePath}/db/sensors/${encodeURIComponent(String(deviceId))}`, body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * 用户注册
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public putUser(body?: Body, observe?: 'body', reportProgress?: boolean): Observable<SimpleStatus>;
  public putUser(body?: Body, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SimpleStatus>>;
  public putUser(body?: Body, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SimpleStatus>>;
  public putUser(body?: Body, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      'application/json'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.put(`${this.basePath}/user`, body,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

}
